AirBnB/Controllers/AccountsController.cs
using AirBnB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirBnB.Models.enums;
using AirBnB.Common;
using AirBnB.DAL;

using System.Data.Entity;

namespace AirBnB.Controllers
{
    public class AccountsController : Controller
    {
        private MyDbContext _context = new MyDbContext();

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        // GET Accounts/Register, registraciona forma
        public ActionResult Register() //registracija GOSTIJU
        {
            if (Session["Id"] == null) //ukoliko niko nije ulogovan, dozvoli pristup registracionoj formi
                return View();
            else
                return View("AlreadyLoggedInError");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User guest) //registracija GOSTIJU
        {
            //var errors = ModelState.Where(x => x.Value.Errors.Count > 0).Select(x => new { x.Key, x.Value.Errors }).ToArray();
            if (!ModelState.IsValid)
                return View();

            var temp = _context.Users.SingleOrDefault(t => t.Username == guest.Username);
            if (temp != null)
                return View("AlreadyExists");

            _context.Users.Add(guest);
            _context.SaveChanges();
            return View("Success");
        }

        public ActionResult Login() 
        {
            if (Session["Id"] == null)  //ako niko nije ulogovan, prikazi login formu
                return View();
            else
                return View("AlreadyLoggedInError");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password)
        {
            //pretraga da li je medju "obicnim" korisnicima
            var usr = _context.Users.SingleOrDefault(u => u.Username == username && u.Password == password);
            if (usr != null)
            {
                Session["Id"] = usr.Id.ToString();
                Session["Username"] = usr.Username;
                Session["Role"] = usr.Role.ToString();
                return View("LoggedIn");
            }
            //ako nije, pretraga da li je medju adminima
            usr = AdminLoad.admins.SingleOrDefault(u => u.Username == username && u.Password == password);
            if (usr != null)
            {
                Session["Id"] = usr.Id.ToString();
                Session["Username"] = usr.Username.ToString();
                Session["Role"] = usr.Role.ToString();
                return View("LoggedIn");
            }
            //ako korisnik ne postoji
            return View("WrongCredentials");
        }

        public ActionResult LogOut()
        {
            if (Session["Id"] != null)
            {
                Session["Id"] = null;
                Session["Username"] = null;
                Session["Role"] = null;
                Session.Abandon();
                return View("Success");
            }
            return HttpNotFound();
        }

        public ActionResult ListUsers(string option, string search, string sort)
        {         
            //listu svih korisnika mogu da vide samo admini
            if (Session["Id"] != null && (string)Session["Role"] == "Admin")
            {
                List<User> users = _context.Users.Where(x => x.IsDeleted == false).ToList();

                #region sort
                ViewBag.SortByUsername = sort == "username" ? "username desc" : "username";
                ViewBag.SortByName = sort == "name" ? "name desc" : "name";
                ViewBag.SortBySurname = sort == "surname" ? "surname desc" : "surname";
                ViewBag.SortByGender = sort == "gender" ? "gender desc" : "gender";
                ViewBag.SortByRole = sort == "role" ? "role desc" : "role";
                #endregion sort
                
                if (option == "Username")
                {
                    users = users.Where(x => x.Username.Contains(search) || search == null).ToList();
                }
                else if (option == "Gender")
                {
                    users = users.Where(x => x.Gender.ToString().ToLower() == search.ToLower() || search == null).ToList();
                }
                else if (option == "Role")
                {
                    users = users.Where(x => x.Role.ToString().ToLower() == search.ToLower() || search == null).ToList();
                }

                var users2 = users.AsQueryable();

                #region sortswitch
                switch (sort)
                {
                    case "username desc":
                        users2 = users2.OrderByDescending(x => x.Username);
                        break;
                    case "username":
                        users2 = users2.OrderBy(x => x.Username);
                        break;
                    case "name desc":
                        users2 = users2.OrderByDescending(x => x.Name);
                        break;
                    case "name":
                        users2 = users2.OrderBy(x => x.Name);
                        break;
                    case "surname desc":
                        users2 = users2.OrderByDescending(x => x.Surname);
                        break;
                    case "surname":
                        users2 = users2.OrderBy(x => x.Surname);
                        break;
                    case "gender desc":
                        users2 = users2.OrderByDescending(x => x.Gender);
                        break;
                    case "gender":
                        users2 = users2.OrderBy(x => x.Gender);
                        break;
                    case "role desc":
                        users2 = users2.OrderByDescending(x => x.Role);
                        break;
                    case "role":
                        users2 = users2.OrderBy(x => x.Role);
                        break;
                    default:
                        users2 = users2.OrderBy(x => x.Id);
                        break;
                }
                #endregion sortswitch

                return View(users2.ToList());
            }
            return View("NotLoggedInError");
        }

        public ActionResult ListAdmins(string option, string search, string sort)
        {
            //listu admina mogu da vide samo ostali admini
            if (Session["Id"] != null && (string)Session["Role"] == "Admin")
            {
                var admins = AdminLoad.admins;
                #region sort
                ViewBag.SortByUsername = sort == "username" ? "username desc" : "username";
                ViewBag.SortByName = sort == "name" ? "name desc" : "name";
                ViewBag.SortBySurname = sort == "surname" ? "surname desc" : "surname";
                ViewBag.SortByGender = sort == "gender" ? "gender desc" : "gender";
                ViewBag.SortByRole = sort == "role" ? "role desc" : "role";
                #endregion sort
                if (option == "Username")
                {
                    admins = admins.Where(x => x.Username.Contains(search) || search == null).ToList();
                }
                else if (option == "Gender")
                {
                    admins = admins.Where(x => x.Gender.ToString().ToLower() == search.ToLower() || search == null).ToList();
                }

                var admins2 = admins.AsQueryable();
                #region sortswitch
                switch (sort)
                {
                    case "username desc":
                        admins2 = admins2.OrderByDescending(x => x.Username);
                        break;
                    case "username":
                        admins2 = admins2.OrderBy(x => x.Username);
                        break;
                    case "name desc":
                        admins2 = admins2.OrderByDescending(x => x.Name);
                        break;
                    case "name":
                        admins2 = admins2.OrderBy(x => x.Name);
                        break;
                    case "surname desc":
                        admins2 = admins2.OrderByDescending(x => x.Surname);
                        break;
                    case "surname":
                        admins2 = admins2.OrderBy(x => x.Surname);
                        break;
                    case "gender desc":
                        admins2 = admins2.OrderByDescending(x => x.Gender);
                        break;
                    case "gender":
                        admins2 = admins2.OrderBy(x => x.Gender);
                        break;
                    default:
                        admins2 = admins2.OrderBy(x => x.Id);
                        break;
                }
                #endregion sortswitch

                return View(admins2.ToList());
            }
            return View("NotLoggedInError");
        }

        public ActionResult Edit()
        {
            if (Session["id"] == null)
                return HttpNotFound();

            string idString = (string)Session["Id"];
            int tempId = int.Parse(idString);
            var user = _context.Users.SingleOrDefault(u => u.Id == tempId);

            if (user != null)
            {   //provera da li je medju reg. userima
                ViewBag.Role = user.Role.ToString();
                return View(user);              
            }
            user = AdminLoad.admins.SingleOrDefault(u => u.Id == tempId);
            if (user != null)//ako nije, provera da li je medju adminima
            {
                ViewBag.Role = user.Role.ToString();
                return View(user);
            }
            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(User user) //edit ne radi za admine
        {

AirBnB/Views/Accounts/AlreadyExists.cshtml
@{
    ViewBag.Title = "AlreadyExists";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>User with that username already exists :(</h2>

AirBnB/Views/Accounts/AlreadyLoggedInError.cshtml
@{
    ViewBag.Title = "AlreadyLoggedInError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You are already logged in.</h2>

AirBnB/Views/Accounts/Edit.cshtml
@model AirBnB.Models.User

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>
<p>My Role is @ViewBag.Role</p>

<form method="post">

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Surname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Surname, new { htmlAttributes = new { @class = "form-control", required = "required" } })
                @Html.ValidationMessageFor(model => model.Surname, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Id)
        @Html.AntiForgeryToken()
        @if ((string)Session["Role"] != "Admin")
        {
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        }

    </div>
</form>

@if ((string)Session["Role"] == "Admin")
{
    <div>
        @Html.ActionLink("Back to List of Users", "ListUsers", "Accounts")
    </div>

}

AirBnB/Views/Accounts/ListAdmins.cshtml
@model IEnumerable<AirBnB.Models.User>

@{
    ViewBag.Title = "ListAdmins";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Admins</h2>

@using (Html.BeginForm("ListAdmins", "Accounts", FormMethod.Get))
{
    //the following are search options
    <b> Search Option:  </b>@Html.RadioButton("option", "Username") <text>Username</text> @Html.RadioButton("option", "Gender") <text>Gender</text>
    @Html.TextBox("search") <input type="submit" name="submit" value="Search" />
    @Html.ActionLink("Reset", "ListAdmins");

}
<br />
<table class="table">
    <tr>
        <th> @Html.ActionLink("Username", "ListAdmins", new { sort = ViewBag.SortByUsername, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th>Password</th>
        <th> @Html.ActionLink("Name", "ListAdmins", new { sort = ViewBag.SortByName, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Surname", "ListAdmins", new { sort = ViewBag.SortBySurname, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Gender", "ListAdmins", new { sort = ViewBag.SortByGender, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>

        </tr>
    }
</table>

AirBnB/Views/Accounts/ListMyApartments.cshtml
@model AirBnB.Models.User

@{
    ViewBag.Title = "ListMyApartments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of my Apartments</h2>

@using (Html.BeginForm("ListMyApartments", "Accounts", FormMethod.Get))
{
    <text> Search options:  </text>
    <input type="radio" value="Location" id="locationOpt" name="option" checked /><label>Location </label>
    <input type="radio" value="Guests" id="guestsOpt" name="option" /><label>Guests </label>
    <input type="radio" value="Rooms" id="roomsOpt" name="option" /><label>Rooms </label>
    <input type="radio" value="Price" id="priceOpt" name="option" /><label>Price </label>
    <label>   </label>

    <div>
        <input type="text" name="search" />
        <input type="submit" name="submit" value="Search" />
        @Html.ActionLink("Reset", "ListMyApartments")
    </div>
    <div id="show-me" hidden>
        <br /><input type="text" name="search2" /><b> (max value)</b>
    </div>
}
<br />

<p>
    @using (Html.BeginForm("ListMyApartments", "Accounts", FormMethod.Get))
    {
        <label>Type </label>
        <select class="ddownColor" id="typeFilter" name="typeFilter">
            <option value="EntirePlace" selected="selected">Entire place</option>
            <option>Room</option>
        </select>
        <button class="ddownColor" type="submit" name="submit" value="TypeFilter">Filter</button>

    }
    @using (Html.BeginForm("ListMyApartments", "Accounts", FormMethod.Get))
    {
        <label>Status </label>
        <select class="ddownColor" id="statusFilter" name="statusFilter">
            <option selected="selected">Active</option>
            <option>Inactive</option>
        </select>
        <button class="ddownColor" type="submit" name="submit" value="StatusFilter">Filter</button>
    }
    @using (Html.BeginForm("ListMyApartments", "Accounts", FormMethod.Get))
    {
        <text>Amenity</text>
        <select class="ddownColor" id="amenityFilter" name="amenityFilter">
            @foreach (var item in ViewBag.Amnts)
            {
                if (item.IsDeleted == false)
                {
                    <option value="@item.Name">@item.Name</option>
                }
            }
        </select>
        <button class="ddownColor" type="submit" name="submit" value="AmenityFilter">Filter</button>
    }
</p>
<br />

<table class="table">
    <tr>
        <th> @Html.ActionLink("Type", "ListMyApartments", new { sort = ViewBag.SortByType, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Price", "ListMyApartments", new { sort = ViewBag.SortByPrice, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Rooms", "ListMyApartments", new { sort = ViewBag.SortByRooms, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Guests", "ListMyApartments", new { sort = ViewBag.SortByGuests, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Status", "ListMyApartments", new { sort = ViewBag.SortByStatus, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("City", "ListMyApartments", new { sort = ViewBag.SortByCity, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Street", "ListMyApartments", new { sort = ViewBag.SortByStreet, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
    </tr>

    @foreach (var apartment in Model.ApartmentsForRent)
    {
    <tr>
        <td>@apartment.Type</td>
        <td>@apartment.Price</td>
        <td>@apartment.NumberOfRooms</td>
        <td>@apartment.NumberOfGuests</td>
        <td>@apartment.Status</td>
        <td>@apartment.Location.Address.City</td>
        <td>@apartment.Location.Address.Street</td>
        <td>
            @Html.ActionLink("Edit", "EditApartmentVM", new { Controller = "Apartments", action = "EditApartmentVM", id = apartment.Id })
        </td>
        <td>
            @Html.ActionLink("Delete", "Delete", new { Controller = "Apartments", action = "Delete", id = apartment.Id })
        </td>
    </tr>
    }
</table>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    $(document).ready(function () {
        $('input[type="radio"]').click(function () {
            if ($(this).attr('id') == 'priceOpt' || $(this).attr('id') == 'roomsOpt') {
                $('#show-me').show();
            }
            else {
                $('#show-me').hide();
            }
        });
    });
</script>

<style>
    #show-me {
        display: none;
    }
    .ddownColor {
        color:black;
        width: 110px;
    }
    label {
        width:70px;
        font-size: 15px;
    }
    button {
        height: 27px
    }
</style>

AirBnB/Views/Accounts/ListUsers.cshtml
@model IEnumerable<AirBnB.Models.User>

@{
    /**/

    ViewBag.Title = "ListUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>List of Users</h2>

@using (Html.BeginForm("ListUsers", "Accounts", FormMethod.Get))
{
    //the following are search options
    <b> Search Option:  </b>@Html.RadioButton("option", "Username") <text>Username</text> @Html.RadioButton("option", "Gender") <text>Gender</text>
    @Html.RadioButton("option", "Role")<text>Role </text> @Html.TextBox("search") <input type="submit" name="submit" value="Search" />
    @Html.ActionLink("Reset", "ListUsers");

}
<br />
<table class="table">
    <tr>
        <th>User id</th>
        <th> @Html.ActionLink("Username", "ListUsers", new { sort = ViewBag.SortByUsername, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th>Password</th>
        <th> @Html.ActionLink("Name", "ListUsers", new { sort = ViewBag.SortByName, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Surname", "ListUsers", new { sort = ViewBag.SortBySurname, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Gender", "ListUsers", new { sort = ViewBag.SortByGender, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Role", "ListUsers", new { sort = ViewBag.SortByRole, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Password)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Role)
            </td>
            
            <td>
                @Html.ActionLink("EDIT", "Edit", new { id = item.Id }) |
                @Html.ActionLink("MAKE HOST", "MakeHost", new { id = item.Id }) |
                @Html.ActionLink("dlt", "Delete", new { id = item.Id }) |
            </td>
        </tr>
    }

</table>

AirBnB/Views/Accounts/LoggedIn.cshtml
@{
    ViewBag.Title = "LoggedIn";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (Session["Id"] != null)
{
    <h3>Welcome @Session["Username"].ToString()!</h3>
}

@if ((string)Session["Role"] == "Host")
{
    @Html.ActionLink("Add a new apartment", "AddApartment", "Apartments");
} <br />

@if ((string)Session["Role"] == "Host")
{
    @Html.ActionLink("List of my apartments", "ListMyApartments", "Accounts");
}

AirBnB/Views/Accounts/Login.cshtml
@model AirBnB.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        margin: 0;
        padding: 0;
    }

    .content {
        width: 25%;
        margin: auto;
    }

    .left {
        width: 30%;
        float: left;
        text-align: right;
    }

    .right {
        width: 65%;
        margin-left: 10px;
        float: left;
        border-radius: 5px;
        padding: 4px;
        height: 30px;
    }

    .signupbutton {
        text-align: center;
        width: 25em;
        background-color: green;
        color: white;
        border-radius: 10px;
        background: #73AD21;
        padding: 5px;
    }

    form {
        margin: auto;
        width: 25em;
        text-align: center;
        position: relative;
    }
</style>

<html>
<body>
    <div style="margin: 0px auto 0px auto; width: 400px">
        <form action="Login" method="post">
            <h1>Log In</h1> <br />
            <fieldset>
                <label class="left" for="username">Username </label>
                <input class="right" type="text" id="username" name="username" required> <br /><br />

                <label class="left" for="password">Password </label>
                <input class="right" type="password" id="password" name="password" required> <br /><br /><br />
                                
                @Html.AntiForgeryToken()
                <button class="signupbutton" type="submit">Login</button>
            </fieldset>
        </form>
    </div>
</body>
@section scripts
{
    @Scripts.Render("~/bundles/jqueryval")
}
</html>

AirBnB/Views/Accounts/LoginAfterRegister.cshtml
@model AirBnB.Models.User

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    * {
        margin: 0;
        padding: 0;
    }

    .content {
        width: 25%;
        margin: auto;
    }

    .left {
        width: 30%;
        float: left;
        text-align: right;
    }

    .right {
        width: 65%;
        margin-left: 10px;
        float: left;
        border-radius: 5px;
        padding: 4px;
        height: 30px;
    }

    .signupbutton {
        text-align: center;
        width: 25em;
        background-color: green;
        color: white;
        border-radius: 10px;
        background: #73AD21;
        padding: 5px;
    }

    form {
        margin: auto;
        width: 25em;
        text-align: center;
        position: relative;
    }
</style>

<html>
<body>
    <div style="margin: 0px auto 0px auto; width: 400px">
        <form action="Login" method="post">
            <h2>You registered as guest successfully! You can log in now.</h2> <br />
            <fieldset>
                <label class="left" for="username">Username </label>
                <input class="right" type="text" id="username" name="username" required> <br /><br />

                <label class="left" for="password">Password </label>
                <input class="right" type="password" id="password" name="password" required> <br /><br /><br />

                <button class="signupbutton" type="submit">Login</button>
            </fieldset>
        </form>
    </div>
</body>
</html>

AirBnB/Views/Accounts/MakeNewHost.cshtml
@{
    ViewBag.Title = "MakeNewHost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    * {
        margin: 0;
        padding: 0;
    }

    .content {
        width: 25%;
        margin: auto;
    }

    .left {
        width: 30%;
        float: left;
        text-align: right;
    }

    .right {
        width: 65%;
        margin-left: 10px;
        float: left;
        border-radius: 5px;
        padding: 4px;
        height: 30px;
    }

    .signupbutton {
        text-align: center;
        width: 25em;
        background-color: green;
        color: white;
        border-radius: 10px;
        background: #73AD21;
        padding: 5px;
    }

    form {
        margin: auto;
        width: 25em;
        text-align: center;
        position: relative;
    }
</style>

<html>
<body>
    <div style="margin: 0px auto 0px auto; width: 400px">
        <form action="MakeNewHost" method="post">
            <h1>Add a new host</h1> <br />
            <fieldset>
                <label class="left" for="username">Username </label>
                <input class="right" type="text" id="username" name="username" required> <br /><br />

                <label class="left" for="name">Name </label>
                <input class="right" type="text" id="name" name="name" required> <br /><br />

                <label class="left" for="surname">Surname </label>
                <input class="right" type="text" id="surname" name="surname" required> <br /><br />

                <label class="left" for="password">Password </label>
                <input class="right" type="password" id="password" name="password" required> <br /><br />

                <label class="left">Gender </label>
                <input type="radio" name="gender" value="male" checked> Male
                <input type="radio" name="gender" value="female"> Female<br><br />

                @Html.AntiForgeryToken()
                <button class="signupbutton" type="submit">Add</button>
            </fieldset>
        </form>
    </div>
</body>
</html>

AirBnB/Views/Accounts/NotLoggedInError.cshtml
@{
    ViewBag.Title = "NotLoggedInError";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>You are not logged in or you don't have authorities needed.</h2>

AirBnB/Views/Accounts/Register.cshtml
@model AirBnB.Models.User

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    * {
        margin: 0;
        padding: 0;
    }

    .content {
        width: 25%;
        margin: auto;
    }

    .left {
        width: 30%;
        float: left;
        text-align: right;
    }

    .right {
        width: 65%;
        margin-left: 10px;
        float: left;
        border-radius: 5px;
        padding: 4px;
        height: 30px;
    }

    .signupbutton {
        text-align: center;
        width: 25em;
        background-color: green;
        color: white;
        border-radius: 10px;
        background: #73AD21;
        padding: 5px;
    }

    form {
        margin: auto;
        width: 25em;
        text-align: center;
        position: relative;
    }
</style>

<html>
<body>
    <div style="margin: 0px auto 0px auto; width: 400px">
        <form action="Register" method="post">
            <h1>Sign Up</h1> <br />
            <div class="left">@Html.LabelFor(model => model.Username)</div>
            <div class="right">@Html.EditorFor(model => model.Username)</div>
            <div>@Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })</div>

            <div class="left">@Html.LabelFor(model => model.Name)</div>
            <div class="right">@Html.EditorFor(model => model.Name)</div>
            <div>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })</div>

            <div class="left">@Html.LabelFor(model => model.Surname)</div>
            <div class="right">@Html.EditorFor(model => model.Surname)</div>
            <div>@Html.ValidationMessageFor(m => Model.Surname)</div>

            <div class="left">@Html.LabelFor(model => model.Password)</div>
            <div class="right">@Html.EditorFor(model => model.Password)</div>
            <div>@Html.ValidationMessageFor(m => Model.Password)</div>

            <div class="left">@Html.LabelFor(model => model.Gender)</div>
            @Html.RadioButtonFor(model => model.Gender, "Male", new { Checked = "checked" })<text>Male</text>
            @Html.RadioButtonFor(model => model.Gender, "Female")<text>Female</text> 

            @Html.AntiForgeryToken()
            <button class="signupbutton" type="submit">Register</button>
        </form>
    </div>
</body>
</html>

AirBnB/Views/Accounts/Success.cshtml
@{
    ViewBag.Title = "Success";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Your action was successful.</h2>

AirBnB/Views/Accounts/WrongCredentials.cshtml
@{
    ViewBag.Title = "WrongCredentials";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Username and/or password invalid.</h2>