AirBnB/Models/Apartment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using AirBnB.Models.enums;

namespace AirBnB.Models
{
    public class Apartment : ISoftDelete
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        [Required]
        public ApartmentType Type { get; set; }
        [Required]
        [Display(Name = "Number of rooms")]
        [Range(0, 15)]
        public int NumberOfRooms { get; set; }
        [Required]
        [Display(Name = "Number of guests")]
        [Range(1, 30)]
        public int NumberOfGuests { get; set; }
        [Required]
        public Location Location { get; set; }
        public List<DateTime> DatesForRent { get; set; } //postavljaju Host-ovi
        public List<DateTime> AvailableDates { get; set; } //sistem automatski generise slobodne datume
        public User Host { get; set; }
        public List<Review> Reviews { get; set; }
        public List<Image> Images { get; set; }
        [Required]
        [Display(Name = "Price in USD")]
        public double Price { get; set; }
        [Required]
        [RegularExpression(@"((1[0-2]|0?[1-9])?([AaPp][Mm]))", ErrorMessage = "Wrong format, use AM/PM")]
        public string CheckIn { get; set; } = "2PM";    //string?
        [Required]
        [RegularExpression(@"((1[0-2]|0?[1-9])?([AaPp][Mm]))", ErrorMessage = "Wrong format, use AM/PM")]
        public string CheckOut { get; set; } = "10AM";
        [Required]
        public ApartmentStatus Status { get; set; }
        public List<Amenity> Amenities { get; set; }
        public List<Booking> Bookings { get; set; }
        public bool IsDeleted { get; set; } = false;
    }
}

AirBnB/Models/enums/ApartmentType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AirBnB.Models.enums
{
    public enum ApartmentType
    {
        EntirePlace,
        Room
    }
}

AirBnB/Controllers/ApartmentsController.cs
using AirBnB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AirBnB.Controllers;
using AirBnB.DAL;
using AirBnB.Models.enums;
using System.IO;
using System.Configuration;
using AirBnB.ViewModels;

namespace AirBnB.Controllers
{
    public class ApartmentsController : Controller
    {
        private MyDbContext _context = new MyDbContext();

        public ActionResult AddApartment()
        {
            if (Session["Id"] != null && (string)Session["Role"] == "Host")
            {
                ApartmantAmenityVM vm = new ApartmantAmenityVM {
                    Apartment = new Apartment(),
                    Amenities = _context.Amenities.Where(x => x.IsDeleted == false).ToList()
                };
                return View(vm);
            }
                
            else
                return HttpNotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddApartment(ApartmantAmenityVM vm, string[] selectedCheckboxes)
        {
            if (!ModelState.IsValid)
            {
                ApartmantAmenityVM temp = new ApartmantAmenityVM
                {
                    Apartment = new Apartment(),
                    Amenities = _context.Amenities.ToList()
                };
                return View(temp);
            }

            vm.Apartment.Status = ApartmentStatus.Inactive; //inicijalno je svaki apartman neaktivan

            string currentUsername = (string)Session["Username"];
            var currentUser = _context.Users.SingleOrDefault(u => u.Username == currentUsername);
            vm.Apartment.Host = currentUser;

            vm.Apartment.Reviews = new List<Review>();  //inicijalno, apartman nema nikakvih komentara

            #region images
            vm.Apartment.Images = new List<Image>();
            List<Image> imgs = vm.Apartment.Images;
            if (imgs == null)
                imgs = new List<Image>();
            if (Request.Files.Count > 0)
            {
                for (int i = 0; i < Request.Files.Count; i++)
                {
                    var file = Request.Files[i];

                    if (file != null && file.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var path = Path.Combine(Server.MapPath("~/Images/"), fileName);

                        file.SaveAs(path);
                        Image tempImg = new Image(fileName, path);
                        imgs.Add(tempImg);
                    }
                }
            }
            vm.Apartment.Images = imgs;
            #endregion images

            #region amenities
            vm.Apartment.Amenities = new List<Amenity>();
            if (selectedCheckboxes != null)
            {
                List<int> ids = selectedCheckboxes.Select(int.Parse).ToList();
                var allAmenities = _context.Amenities.ToList();
                foreach (int index in ids)
                {
                    var a = allAmenities.Find(x => x.Id == index);
                    vm.Apartment.Amenities.Add(a);
                }
            }        
            #endregion amenities

            //mozda moze i bez ove linije?
            //currentUser.ApartmentsForRent.Add(vm.Apartment);
            _context.Apartments.Add(vm.Apartment);
            _context.SaveChanges();

            return View("Success");
        }

        public ActionResult ListAllApartments(string option, string search, string search2, string sort, string typeFilter, string statusFilter, string submit, string amenityFilter)
        {                     
            if (Session["Id"] != null && (string)Session["Role"] == "Admin")
            {
                var apts = _context.Apartments.Include("Host").Include("Amenities").Include("Location.Address").Where(x => x.IsDeleted == false).ToList();

                #region sort
                ViewBag.SortByCity = sort == "city" ? "city desc" : "city";
                ViewBag.SortByPrice = sort == "price" ? "price desc" : "price";
                ViewBag.SortByType = sort == "type" ? "type desc" : "type";
                ViewBag.SortByStreet = sort == "street" ? "street desc" : "street";
                ViewBag.SortByGuests = sort == "guests" ? "guests desc" : "guests";
                ViewBag.SortByRooms = sort == "rooms" ? "rooms desc" : "rooms";
                ViewBag.SortByHost = sort == "host" ? "host desc" : "host";
                ViewBag.SortByStatus = sort == "status" ? "status desc" : "status";
                #endregion sort

                ViewBag.AptTypes = Enum.GetValues(typeof(ApartmentType)).Cast<ApartmentType>();
                ViewBag.Statuses = Enum.GetValues(typeof(ApartmentStatus)).Cast<ApartmentStatus>();
                ViewBag.Amnts = _context.Amenities.ToList();

                int temp;

                if (option == "Location")
                        apts = apts.Where(x => x.Location.Address.City.Contains(search)
                                || x.Location.Address.Street.Contains(search)
                                || search == null).ToList();                    
                else if (option == "Guests")
                    if (int.TryParse(search, out temp))
                        apts = apts.Where(x => x.NumberOfGuests == Int32.Parse(search) || search == null).ToList();
                    else
                        apts = apts.ToList();
                else if (option == "Rooms")
                    if (int.TryParse(search, out temp) && int.TryParse(search2, out temp))
                        apts = apts.Where(x => x.NumberOfRooms >= Int32.Parse(search) && x.NumberOfRooms <= Int32.Parse(search2)).ToList();
                    else
                        apts = apts.ToList();
                else if (option == "Price")
                    if (int.TryParse(search, out temp) && int.TryParse(search2, out temp))
                        apts = apts.Where(x => x.Price >= Int32.Parse(search) && x.Price <= Int32.Parse(search2)).ToList();
                    else
                        apts = apts.ToList();

                var apts2 = apts.AsQueryable();

                #region sortswitch
                switch (sort)
                {
                    case "city desc":
                        apts2 = apts2.OrderByDescending(x => x.Location.Address.City);
                        break;
                    case "city":
                        apts2 = apts2.OrderBy(x => x.Location.Address.City);
                        break;
                    case "price desc":
                        apts2 = apts2.OrderByDescending(x => x.Price);
                        break;
                    case "price":
                        apts2 = apts2.OrderBy(x => x.Price);
                        break;
                    case "type desc":
                        apts2 = apts2.OrderByDescending(x => x.Type.ToString());
                        break;
                    case "type":
                        apts2 = apts2.OrderBy(x => x.Type);
                        break;
                    case "street desc":
                        apts2 = apts2.OrderByDescending(x => x.Location.Address.Street);
                        break;
                    case "street":
                        apts2 = apts2.OrderBy(x => x.Location.Address.Street);
                        break;
                    case "guests desc":
                        apts2 = apts2.OrderByDescending(x => x.NumberOfGuests);
                        break;
                    case "guests":
                        apts2 = apts2.OrderBy(x => x.NumberOfGuests);
                        break;
                    case "rooms desc":
                        apts2 = apts2.OrderByDescending(x => x.NumberOfRooms);
                        break;
                    case "rooms":
                        apts2 = apts2.OrderBy(x => x.NumberOfRooms);
                        break;
                    case "host desc":
                        apts2 = apts2.OrderByDescending(x => x.Host.Username);
                        break;
                    case "host":
                        apts2 = apts2.OrderBy(x => x.Host.Username);
                        break;
                    case "status desc":
                        apts2 = apts2.OrderByDescending(x => x.Status);
                        break;
                    case "status":
                        apts2 = apts2.OrderBy(x => x.Status);
                        break;
                    default:
                        apts2 = apts2.OrderBy(x => x.Id);
                        break;
                }
                #endregion sortswitch

                if (submit == "TypeFilter")
                {
                    if (typeFilter == "EntirePlace")
                        return View(apts.Where(x => x.Type == ApartmentType.EntirePlace));
                    else if (typeFilter == "Room")
                        return View(apts.Where(x => x.Type == ApartmentType.Room));
                }
                else if (submit == "StatusFilter")
                {
                    if (statusFilter == "Active")
                        return View(apts.Where(x => x.Status == ApartmentStatus.Active));
                    else if (statusFilter == "Inactive")
                        return View(apts.Where(x => x.Status == ApartmentStatus.Inactive));
                }
                else if (submit == "AmenityFilter")
                {
                    foreach (var item in _context.Amenities.ToList())
                        if (amenityFilter == item.Name)
                            return View(apts.Where(x => x.Amenities.Contains(item)));
                }

                return View(apts2.ToList());
            }
            else
                return HttpNotFound();
        }

        public ActionResult EditApartmentVM(int id)
        {

AirBnB/Views/Apartments/ApartmentDetails.cshtml
@model AirBnB.Models.Apartment

@{
    ViewBag.Title = "ApartmentDetails";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    <h3>Apartment @Model.Id details</h3>

    @if ((string)Session["Role"] == "Admin" || (string)Session["Role"] == "Host")
    {
        <p>
            @Html.ActionLink("Back to all apartments", "ListAllApartments")
        </p>
    }
    else 
    {
        <p>
            @Html.ActionLink("Back to all apartments", "ListApartmentsLoggedOut")
        </p>
    }

    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            Rooms
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfRooms)
        </dd>

        <dt>
            Max guests
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NumberOfGuests)
        </dd>

        <dt>
            Price($) per night
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            Check-in time
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CheckIn)
        </dd>

        <dt>
            Check-out time
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CheckOut)
        </dd>

        <dt>Address</dt>
        <dd>
            @Html.DisplayFor(model => model.Location.Address.Street)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Location.Address.Number)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Location.Address.PostalCode)
        </dd>
        <dd>
            @Html.DisplayFor(model => model.Location.Address.City)
        </dd>

        <dt>Host's usernname</dt>
        <dd>
            @Html.DisplayFor(model => model.Host.Username)
        </dd>

        <dt>Status</dt>
        <dd>@Html.DisplayFor(model => model.Status)</dd>

        <dt>@Html.ActionLink("Reviews", "ViewApartmentReviews", new { id = Model.Id }) </dt>
        <dd>
        </dd>

        <dt>@Html.ActionLink("Amenities", "ViewApartmentAmenities", new { id = Model.Id })</dt>
        <dd></dd>

        <dt>@Html.ActionLink("Images", "ViewApartmentImages", new { id = Model.Id })</dt>
        <dd></dd>
    </dl>
</div>

AirBnB/Views/Apartments/EditApartmentVM.cshtml
@model AirBnB.ViewModels.ApartmantAmenityVM

@{
    ViewBag.Title = "EditApartmentVM";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("EditApartment", "Apartments", FormMethod.Post))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Apartment</h4>
    id - @Model.Apartment.Id
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(Model => Model.Apartment.Id)

    @if ((string)Session["Role"] == "Host")
    {
        <p>@Html.ActionLink("Back to my apartments", "ListMyApartments", "Accounts")</p>
    }
    else if ((string)Session["Role"] == "Admin")
    {
        <p>@Html.ActionLink("Back to all apartments", "ListAllApartments", "Apartments")</p>
    }

    <div class="form-group">
        <label class="control-label col-md-2">Type</label>
        <div class="col-md-10">
            Room @Html.RadioButtonFor(model => model.Apartment.Type, "Room")
            Entire place @Html.RadioButtonFor(model => model.Apartment.Type, "EntirePlace")
            <!--<input type="radio" name="Apartment.Type" value="EntirePlace"> Entire place<br>-->
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.NumberOfRooms, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.NumberOfRooms, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.NumberOfRooms, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.NumberOfGuests, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.NumberOfGuests, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.NumberOfGuests, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.CheckIn, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.CheckIn, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.CheckIn, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.CheckOut, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.CheckOut, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.CheckOut, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">Status</label>
        <div class="col-md-10">
            Active @Html.RadioButtonFor(model => model.Apartment.Status, "Active")
            Inactive @Html.RadioButtonFor(model => model.Apartment.Status, "Inactive")
            <!--<input type="radio" name="Apartment.Type" value="EntirePlace"> Entire place<br>-->
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Longitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Longitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Latitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Latitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Address.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Address.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Address.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Address.Number, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Address.Number, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Address.Number, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Address.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Address.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Apartment.Location.Address.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Apartment.Location.Address.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Apartment.Location.Address.PostalCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">
            @Html.ActionLink("Amenities", "EditAptAmenities", new { id = Model.Apartment.Id })
        </label>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">
            @Html.ActionLink("Reviews", "EditAptReviews", new { id = Model.Apartment.Id })
        </label>
    </div>

    <div class="form-group">
        <label class="control-label col-md-2">
            @Html.ActionLink("Images", "EditAptImages", new { id = Model.Apartment.Id })
        </label>
    </div>


    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AirBnB/Views/Apartments/EditAptImages.cshtml
@model IEnumerable<AirBnB.Models.Image>

@{
    ViewBag.Title = "ViewApartmentImages";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Apartment Images</h3>
<p>*to delete a picture, check the box before it.</p>
<p>
    @Html.ActionLink("Back to apartment info", "EditApartmentVM", new { id = ViewBag.AptId })
</p>
<form action="@Url.Action("DeleteAptImages", "Apartments", new { id = ViewBag.AptId } )" method="post" enctype="multipart/form-data">

    @foreach (var image in Model)
    {
    <input type="checkbox" width="10" name="selectedCheckboxes" value="@image.Id" />
    <img src="~/Images/@image.Name" height="150" width="200" />
    }
    <br /><br />
    <input name="AptId" value=@ViewBag.AptId hidden />
    @Html.AntiForgeryToken()
    <input type="submit" value="Delete" />
</form>

    <br />
    <form action="@Url.Action("AddAptImages", "Apartments", new { id = ViewBag.AptId } )" method="post" enctype="multipart/form-data">
        <p>Add new images</p>
        <input class="right" type="file" name="file" multiple="multiple" /> <br />
        <input name="AptId" value=@ViewBag.AptId hidden />
        @Html.AntiForgeryToken()
        <input type="submit" value="Add" />
    </form>

AirBnB/Views/Apartments/EditAptReviewsAdmin.cshtml
@model AirBnB.Models.Apartment
@{
                /**/

                ViewBag.Title = "EditAptReviews";
                Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Apartment Reviews</h2>

<p>
    @Html.ActionLink("Back to apartment", "EditApartmentVM", new { id = ViewBag.AptId })
</p>
<table class="table">
    <tr>
        <th>
            Who wrote it
        </th>
        <th>
            Comment
        </th>
        <th>
            Rating
        </th>
        <th>Hidden?</th>
    </tr>

    @foreach (var item in Model.Reviews)
    {
        <tr>
            <td>@item.Guest.Username</td>
            <td>@item.Comment</td>
            <td>@item.Rating</td>
            <td>@item.IsHidden</td>
        </tr>
    }

</table>

AirBnB/Views/Apartments/ListAllApartments.cshtml
@model IEnumerable<AirBnB.Models.Apartment>

@{
    ViewBag.Title = "ListAllApartments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ListAllApartments</h2>

@using (Html.BeginForm("ListAllApartments", "Apartments", FormMethod.Get))
{
    <b> Search options:  </b>
    <input type="radio" value="Location" id="locationOpt" name="option" checked /><label>Location </label>
    <input type="radio" value="Guests" id="guestsOpt" name="option" /><label>Guests </label>
    <input type="radio" value="Rooms" id="roomsOpt" name="option" /><label>Rooms </label>
    <input type="radio" value="Price" id="priceOpt" name="option" /><label>Price </label>

    <div>
        <input type="text" name="search" />
        <input type="submit" name="submit" value="Search" />
        @Html.ActionLink("Reset", "ListAllApartments")
    </div>
    <div id="show-me" hidden>
        <br /><input type="text" name="search2" /><b> (min-max)</b>
    </div>
}
<br />

<p>
    @using (Html.BeginForm("ListAllApartments", "Apartments", FormMethod.Get))
    {
        <label>Type </label>
        <select class="ddownColor" id="typeFilter" name="typeFilter">
            <option value="EntirePlace" selected="selected">Entire place</option>
            <option>Room</option>
        </select>
        <button class="ddownColor" type="submit" name="submit" value="TypeFilter">Filter</button>
    }
    @using (Html.BeginForm("ListAllApartments", "Apartments", FormMethod.Get))
    {
        <label>
            Status
        </label>
        <select class="ddownColor" id="statusFilter" name="statusFilter">
            <option selected="selected">Active</option>
            <option>Inactive</option>
        </select>
        <button class="ddownColor" type="submit" name="submit" value="StatusFilter">Filter</button>
    }
    @using (Html.BeginForm("ListAllApartments", "Apartments", FormMethod.Get))
    {
        <text>Amenity</text>
        <select class="ddownColor" id="amenityFilter" name="amenityFilter">
            @foreach (var item in ViewBag.Amnts)
            {
                if (item.IsDeleted == false)
                {
                    <option value="@item.Name">@item.Name</option>
                }
            }
        </select>
        <button class="ddownColor" type="submit" name="submit" value="AmenityFilter">Filter</button>
    }

</p>

<table class="table">
    <tr>
        <th> @Html.ActionLink("Type", "ListAllApartments", new { sort = ViewBag.SortByType, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Host", "ListAllApartments", new { sort = ViewBag.SortByHost, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Price", "ListAllApartments", new { sort = ViewBag.SortByPrice, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Rooms", "ListAllApartments", new { sort = ViewBag.SortByRooms, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Guests", "ListAllApartments", new { sort = ViewBag.SortByGuests, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Status", "ListAllApartments", new { sort = ViewBag.SortByStatus, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("City", "ListAllApartments", new { sort = ViewBag.SortByCity, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
        <th> @Html.ActionLink("Street", "ListAllApartments", new { sort = ViewBag.SortByStreet, option = Request.QueryString["option"], search = Request.QueryString["search"] }) </th>
    </tr>

    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Host.Username)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfRooms)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumberOfGuests)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location.Address.City)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location.Address.Street)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditApartmentVM", new { Controller = "Apartments", action = "EditApartmentVM", id = item.Id })|
            @Html.ActionLink("Details", "ApartmentDetails", new { Controller = "Apartments", action = "ApartmentDetails", id = item.Id })|
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
    }
</table>

<script src="~/Scripts/jquery-3.3.1.js"></script>
<script>
    $(document).ready(function () {
        $('input[type="radio"]').click(function () {
            if ($(this).attr('id') == 'priceOpt' || $(this).attr('id') == 'roomsOpt') {
                $('#show-me').show();
            }
            else {
                $('#show-me').hide();
            }
        });
    });
</script>

<style>
    #show-me {
        display: none;
    }

    .ddownColor {
        color: black;
        width: 110px;
    }

    label {
        width: 70px;
        font-size: 15px;
    }

    button {
        height: 27px;
    }
</style>